[package]
name = "lfanalysis-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
lfanalysis = { version = "0.1.0", path = "../lfanalysis" }
lfdeploy = { version = "0.1.0", path = "../lfdeploy" }
wasm-bindgen = "0.2"
