[package]
name = "lfbuildconfig"
version = "0.1.0"
edition = "2021"

[dependencies]
lingo = { version = "0.2.0", path = "../lingo", default-features = false }
wasm-bindgen = "0.2.91"
web-sys = "0.3.68"
